name: learnai-aml

dependencies:
  - python=3.6.1

  - pip:
    - azureml-sdk[automl]
    - https://download.pytorch.org/whl/cu90/torch-1.0.0-cp36-cp36m-win_amd64.whl
    - torchvision
    - pylint
    - matplotlib
    - seaborn
    - pyculiarity
    - pytictoc
    